server:
  port: 6000

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/account
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace